### ISSUE TITLE
output中的embed_input有用到ground truth是否還是unsupervised？

### ISSUE THREAD

**Issue by GarlicWang** [qizhyuan/PRASE-Python#1]
您好，想請教一下：

- PRASE分成PR module & SE module，不過 PARIS code 中PR module有一個input是ground truth要輸入ent_links，而這個link並不會在PR module被使用，而是用於之後傳給SE module的valid_links及test_links，所以PR module是unsupervised method。不過SE module是使用OpenEA這個embedding-based method，輸入的valid_link會用於更新參數，換言之，OpenEA仍是一個supervised method。如此一來，貌似只有PR module是unsupervised、而SE module卻是supervised，PRASE作為一個整合PR & SE的方法應該算是supervised？  
- 另外從您的論文的Figure1看來SE module的input應該是Alignment seed(train_links)以及Unaligned Candidates，不過code好像沒有輸出Unaligned Candidates的部分

謝謝

**Comment by qizhyuan** [comment]
您好，

1. OpenEA本身确实是supervised method。但在我们的框架中，它的输入实际上是由PR模型的输出构建的。我们将PR模型的输出筛选后当作是ground truth用于训练SE模型。整个框架本身并没用从外界获取任何额外的mapping信息，所以PRASE是无监督的。
2. 这份代码里没有涉及到SE模型部分，如需运行完整的框架，需要修改OpenEA的代码。您说的“Unaligned Candidates”部分的逻辑实现其实可以写到SE模型的代码里。当然您也可以直接在这份代码上修改增加输出“Unaligned Candidates”。

如需了解整个系统的运行流程，可以参考 https://github.com/qizhyuan/PRASEMap 这份代码。这份代码本身集成了GCNAlign这个简单的SE模型，且PR模型部分底层是由C++实现的，运行速度极快。当然配置起来要稍微麻烦一些。

祝好！
