### ISSUE TITLE
data文件

### ISSUE THREAD

**Issue by TiAmoBi** [qizhyuan/PRASE-Python#2]
您好，
       想请问一下，在data下BootEA中的所有文件，是您运行OpenEA所得到的输出文件吗？
谢谢！

**Comment by qizhyuan** [comment]
你好，

这些文件是基于OpenEA生成的！但需要对OpenEA进行简单改动。OpenEA的alignment_results_12文件里存的是实体的index，且省略了实体对齐的概率，而我们data中的alignment_results_12将index重新映射回了实体，且加上了实体对齐的概率。你可以运行一下OpenEA然后对比其输出和我们data文件夹下的相应文件。

具体来说，可能需要对OpenEA做如下改动：
1. 在OpenEA里创建index到实体的dict（比如在OpenEA的KGs class的构造函数里加）。再在保存时（参见OpenEA模型的testl方法下if save里的代码）将index重新映射回实体名保存。
2. 在对齐时也输出对齐的概率：这可能需要改动OpenEA里的evaluation.py和alignment.py让返回对齐结果时也返回对齐的概率，并在保存时输出。

希望能够帮到你。
